### PR TITLE
fix: Numeric value out of range error

### LINKED ISSUE #45: Bug: Numeric value out of range error
> Response data: {success: false, message: Failed to create transaction, errors: [SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'amount' at row 1 (Connection: mysql, SQL: insert into transactions (amount, type, description, datetime, created_at, party_id, wallet_id, user_id, updated_at) values (8000000, income, mnnnnnn, 2025-05-14 21:24:43, 2025-05-14 21:24:54, ?, ?, 15, 2025-05-15 06:44:56))]}

### PR DESCRIPTION
**Pull request by kofimokome**
Fixes #45

### CODE REVIEW

File: database/migrations/2024_07_20_125117_create_transactions_table.php [hunk 1]
```diff
@@ -13,7 +13,7 @@ public function up(): void
     {
         Schema::create('transactions', function (Blueprint $table) {
             $table->id();
-            $table->float('amount');
+            $table->decimal('amount', 15, 2);
```
Comment (nfebe) [inline database/migrations/2024_07_20_125117_create_transactions_table.php:16]:
```suggestion
            $table->decimal('amount', 18, 4);
```

**Review by nfebe — APPROVED** [review]
